#!/usr/bin/env ruby

require 'optparse'

TerraformTemplateDir = File.dirname($0)
LibDir = File.realpath(__dir__)

opts_parser = OptionParser.new do |opts|
	opts.on('-eENV', '--environment=ENV') {|env| EnvironmentName=env }
end

if ENV['AWS_ENV']
	EnvironmentName ||= ENV['AWS_ENV']
end

passthrough_opts = []
	# anything not for this script, we will pass on to the actual summarizer

begin
	opts_parser.parse!
rescue OptionParser::InvalidOption => e
	passthrough_opts << e.args
	retry
end

exec "\"#{File.join(LibDir, 'summarize-planning-output')}\" #{passthrough_opts.flatten.join(' ')} < \"#{TerraformTemplateDir}/environments/#{EnvironmentName}/result.planning\""
